/* soapedeliveryApiBindingService.cpp
   Generated by gSOAP 2.8.3 from delivery2Service.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapedeliveryApiBindingService.h"

edeliveryApiBindingService::edeliveryApiBindingService()
{	edeliveryApiBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

edeliveryApiBindingService::edeliveryApiBindingService(const struct soap &_soap) : soap(_soap)
{ }

edeliveryApiBindingService::edeliveryApiBindingService(soap_mode iomode)
{	edeliveryApiBindingService_init(iomode, iomode);
}

edeliveryApiBindingService::edeliveryApiBindingService(soap_mode imode, soap_mode omode)
{	edeliveryApiBindingService_init(imode, omode);
}

edeliveryApiBindingService::~edeliveryApiBindingService()
{ }

void edeliveryApiBindingService::edeliveryApiBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://edelivery2.localhost/ws/edeliveryApi/1.0/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
};

void edeliveryApiBindingService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

#ifndef WITH_PURE_VIRTUAL
edeliveryApiBindingService *edeliveryApiBindingService::copy()
{	edeliveryApiBindingService *dup = SOAP_NEW_COPY(edeliveryApiBindingService(*(struct soap*)this));
	return dup;
}
#endif

int edeliveryApiBindingService::soap_close_socket()
{	return soap_closesock(this);
}

int edeliveryApiBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int edeliveryApiBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int edeliveryApiBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int edeliveryApiBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void edeliveryApiBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void edeliveryApiBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *edeliveryApiBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void edeliveryApiBindingService::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *edeliveryApiBindingService::soap_header()
{	return this->header;
}

int edeliveryApiBindingService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()))
				return this->error;
			(void)serve();
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET edeliveryApiBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET edeliveryApiBindingService::accept()
{	return soap_accept(this);
}

int edeliveryApiBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if (dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_ns1__getDataForBku(edeliveryApiBindingService*);
static int serve_ns1__setSppConfirmation(edeliveryApiBindingService*);

int edeliveryApiBindingService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "ns1:getDataForBku"))
		return serve_ns1__getDataForBku(this);
	if (!soap_match_tag(this, this->tag, "ns1:setSppConfirmation"))
		return serve_ns1__setSppConfirmation(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_ns1__getDataForBku(edeliveryApiBindingService *soap)
{	struct ns1__getDataForBku soap_tmp_ns1__getDataForBku;
	struct ns1__getDataForBkuResponse _param_1;
	soap_default_ns1__getDataForBkuResponse(soap, &_param_1);
	soap_default_ns1__getDataForBku(soap, &soap_tmp_ns1__getDataForBku);
	soap->encodingStyle = NULL;
	if (!soap_get_ns1__getDataForBku(soap, &soap_tmp_ns1__getDataForBku, "ns1:getDataForBku", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->getDataForBku(soap_tmp_ns1__getDataForBku._org_USCOREkd, soap_tmp_ns1__getDataForBku._keterangan, soap_tmp_ns1__getDataForBku._timestamp, _param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__getDataForBkuResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getDataForBkuResponse(soap, &_param_1, "ns1:getDataForBkuResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getDataForBkuResponse(soap, &_param_1, "ns1:getDataForBkuResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__setSppConfirmation(edeliveryApiBindingService *soap)
{	struct ns1__setSppConfirmation soap_tmp_ns1__setSppConfirmation;
	struct ns1__setSppConfirmationResponse _param_2;
	soap_default_ns1__setSppConfirmationResponse(soap, &_param_2);
	soap_default_ns1__setSppConfirmation(soap, &soap_tmp_ns1__setSppConfirmation);
	soap->encodingStyle = NULL;
	if (!soap_get_ns1__setSppConfirmation(soap, &soap_tmp_ns1__setSppConfirmation, "ns1:setSppConfirmation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->setSppConfirmation(soap_tmp_ns1__setSppConfirmation._xml_USCOREparams, _param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__setSppConfirmationResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__setSppConfirmationResponse(soap, &_param_2, "ns1:setSppConfirmationResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__setSppConfirmationResponse(soap, &_param_2, "ns1:setSppConfirmationResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
