/* soapedeliveryApiBindingProxy.h
   Generated by gSOAP 2.8.3 from delivery2Service.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapedeliveryApiBindingProxy_H
#define soapedeliveryApiBindingProxy_H
#include "soapH.h"

class SOAP_CMAC edeliveryApiBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'edeliveryApiBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	edeliveryApiBindingProxy();
	/// Constructor with copy of another engine state
	edeliveryApiBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	edeliveryApiBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	edeliveryApiBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	edeliveryApiBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	edeliveryApiBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~edeliveryApiBindingProxy();
	/// Initializer used by constructors
	virtual	void edeliveryApiBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'getDataForBku' (returns error code or SOAP_OK)
	virtual	int getDataForBku(std::string _org_USCOREkd, std::string _keterangan, time_t _timestamp, struct ns1__getDataForBkuResponse &_param_1) { return getDataForBku(NULL, NULL, _org_USCOREkd, _keterangan, _timestamp, _param_1); }
	virtual	int getDataForBku(const char *endpoint, const char *soap_action, std::string _org_USCOREkd, std::string _keterangan, time_t _timestamp, struct ns1__getDataForBkuResponse &_param_1);

	/// Web service operation 'setSppConfirmation' (returns error code or SOAP_OK)
	virtual	int setSppConfirmation(std::string _xml_USCOREparams, struct ns1__setSppConfirmationResponse &_param_2) { return setSppConfirmation(NULL, NULL, _xml_USCOREparams, _param_2); }
	virtual	int setSppConfirmation(const char *endpoint, const char *soap_action, std::string _xml_USCOREparams, struct ns1__setSppConfirmationResponse &_param_2);
};
#endif
